"use client"

import { useEffect, useState } from "react"
import { CreditCard, Send, X } from "lucide-react"
import { render } from "@react-email/render"
import { useMutation, useQuery } from "convex/react"
import { api } from "@/lib/convex/api"
import PaymentReminderEmail from "@/lib/email/templates/payment-reminder"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export function PaymentReminderCard(props: { eventId: string; eventTitle: string; eventDate: number; audienceTotal: number; selectedCount: number; allMatching: boolean; canSend: boolean; onSelectAll: () => void; onClear: () => void; onSendRequest: () => void }) {
  const settings = useQuery(api.paymentReminders.getSettings, { eventId: props.eventId as never })
  const updateSettings = useMutation(api.paymentReminders.updateSettings)
  const history = useQuery(api.paymentReminders.getReminderHistory, { eventId: props.eventId as never })
  const [enabled, setEnabled] = useState(false); const [automaticEnabled, setAutomaticEnabled] = useState(false); const [dueAt, setDueAt] = useState(""); const [cadenceMinutes, setCadenceMinutes] = useState("1440"); const [repeatPolicy, setRepeatPolicy] = useState<"oncePerPeriod" | "onceEver">("oncePerPeriod"); const [preview, setPreview] = useState<string | null>(null)
  useEffect(() => { if (settings) { setEnabled(settings.enabled); setAutomaticEnabled(settings.automaticEnabled); setDueAt(new Date(settings.dueAt).toISOString().slice(0, 16)); setCadenceMinutes(String(settings.cadenceMinutes)); setRepeatPolicy(settings.repeatPolicy) } }, [settings])
  useEffect(() => { render(PaymentReminderEmail({ kind: "unpaid", eventName: props.eventTitle, eventDate: new Date(props.eventDate).toLocaleDateString("en-GB"), bookerName: "Example booker", bookingRef: "BK-EXAMPLE", amountDueMinor: 10000, paidAmountMinor: 0, outstandingAmountMinor: 10000, currency: "EUR", managePaymentUrl: `${window.location.origin}/booking/BK-EXAMPLE/manage` })).then(setPreview).catch(() => setPreview(null)) }, [props.eventTitle, props.eventDate])
  async function save() { await updateSettings({ eventId: props.eventId as never, enabled, automaticEnabled, dueAt: new Date(dueAt).getTime(), timezone: "UTC", cadenceMinutes: Number(cadenceMinutes), repeatPolicy }) }
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><CreditCard className="size-4 text-primary" />Payment reminders</CardTitle></CardHeader><CardContent className="space-y-4"><div className="overflow-hidden rounded-xl border">{preview ? <iframe title="Payment reminder preview" srcDoc={preview} className="h-80 w-full" /> : <p className="p-4 text-sm text-muted-foreground">Preview unavailable</p>}</div><div className="grid gap-3 sm:grid-cols-2"><label className="flex gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} /> Enable reminders</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={automaticEnabled} onChange={e => setAutomaticEnabled(e.target.checked)} /> Automatic reminders</label><label className="text-sm">Due instant<input className="mt-1 w-full rounded border p-2" type="datetime-local" value={dueAt} onChange={e => setDueAt(e.target.value)} /></label><label className="text-sm">Cadence (minutes)<input className="mt-1 w-full rounded border p-2" type="number" min="1" value={cadenceMinutes} onChange={e => setCadenceMinutes(e.target.value)} /></label><label className="text-sm">Repeat policy<select className="mt-1 w-full rounded border p-2" value={repeatPolicy} onChange={e => setRepeatPolicy(e.target.value as typeof repeatPolicy)}><option value="oncePerPeriod">Once per period</option><option value="onceEver">Once ever</option></select></label></div><div className="flex flex-wrap items-center gap-2"><Button type="button" variant="outline" onClick={save}>Save reminder policy</Button><span className="text-xs text-muted-foreground">{props.selectedCount} selected{props.allMatching ? " (all matches)" : ""}</span><Button type="button" variant="outline" size="sm" onClick={props.onSelectAll}>Select all matches</Button><Button type="button" variant="ghost" size="sm" onClick={props.onClear}><X className="size-3" />Clear</Button><Button type="button" onClick={props.onSendRequest} disabled={!props.canSend}><Send className="size-4" />Queue reminders</Button></div><div className="text-xs text-muted-foreground">{history?.length ?? 0} reminder campaigns recorded. Amounts and eligibility are rechecked by the server.</div></CardContent></Card>
}
