import { Body, Button, Container, Heading, Html, Img, Preview, Section, Text } from "@react-email/components"
import type { PaymentReminderKind } from "../../domain/payment-reminders"
import { PAYMENT_REMINDER_COPY } from "../payment-reminder-copy"

export default function PaymentReminderEmail(props: { kind: PaymentReminderKind; eventName: string; eventDate: string; bookerName: string; bookingRef: string; amountDueMinor: number; paidAmountMinor: number; outstandingAmountMinor: number; currency: string; managePaymentUrl: string }) {
  const copy = PAYMENT_REMINDER_COPY[props.kind]
  const money = (minor: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: props.currency }).format(minor / 100)
  return <Html lang="en"><Preview>{copy.subject}</Preview><Body style={{ margin: 0, padding: "24px 12px", backgroundColor: "#f4f5f7", fontFamily: "Arial, sans-serif" }}><Container style={{ maxWidth: 600, margin: "0 auto", backgroundColor: "#fff", border: "1px solid #e5e7eb", borderRadius: 12, overflow: "hidden" }}><Section style={{ padding: "28px", backgroundColor: "#0f172a", color: "#fff" }}><Img src={`${process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"}/dlbc-logo.png`} width="48" height="48" alt="DCLM NL Conference" /><Heading style={{ marginBottom: 8 }}>{copy.subject}</Heading><Text style={{ color: "#cbd5e1" }}>{copy.message}</Text></Section><Section style={{ padding: "28px" }}><Text>Hi {props.bookerName},</Text><Text><strong>{props.eventName}</strong><br />{props.eventDate}<br />Booking reference: <strong>{props.bookingRef}</strong></Text><Text>Amount due: <strong>{money(props.amountDueMinor)}</strong><br />Paid: <strong>{money(props.paidAmountMinor)}</strong><br />Outstanding: <strong>{money(props.outstandingAmountMinor)}</strong></Text><Button href={props.managePaymentUrl} style={{ display: "block", padding: "14px", textAlign: "center", backgroundColor: "#4f46e5", color: "#fff", borderRadius: 8, textDecoration: "none" }}>Manage booking and payment</Button></Section><Section style={{ padding: "18px 28px", borderTop: "1px solid #e5e7eb" }}><Text style={{ color: "#6b7280", fontSize: 12 }}>This email was sent by DCLM NL Conference.</Text></Section></Container></Body></Html>
}
